myMood/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    search_field = StringField(validators=[DataRequired()])

    search = SubmitField()

myMood/stories/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired


class NewStoryForm(FlaskForm):
    content = TextAreaField(validators=[DataRequired()])
    emotion = SelectField(
        choices=[
            ("default", "😃 Feeling..."),
            ("happy", "😀 Happy"),
            ("blessed", "😇 Blessed"),
            ("loved", "😍 Loved"),
            ("lovely", "😊 Lovely"),
            ("sad", "🙁 Sad"),
            ("surprised", "😱 Surprised"),
            ("angry", "😡 Angry"),
            ("excited", "😁 Excited"),
            ("embarassed", "😳 Embarrased"),
            ("thankful", "🤗 Thankful"),
            ("in_love", "🥰 In Love"),
            ("crazy", "😆 Crazy"),
            ("sick", "🤒 Sick"),
            ("tired", "😓 Tired"),
            ("sleepy", "🥱 Sleepy"),
        ]
    )
    state = SelectField(choices=[("private", "Private"), ("public", "Public")])

    post = SubmitField("Post")

myMood/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from flask_migrate import Migrate
from flask_compress import Compress
from flask_assets import Environment, Bundle
from flask_caching import Cache

# import pylibmc
# from flask_session import Session
from myMood.config import ProdConfig, DevConfig
import os

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = "users.user_login"
login_manager.login_message_category = "blue"
login_manager.session_protection = "strong"
mail = Mail()
compress = Compress()
cache = Cache()
assets = Environment()
# sess = Session()


def create_app(config_class=DevConfig):
    app = Flask(__name__)
    app.config.from_object(DevConfig)
    migrate = Migrate(app, db)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    compress.init_app(app)
    assets.init_app(app)
    # sess.init_app(app)

    css = Bundle("css/build.css")
    assets.register("main_css", css)

    cache.init_app(app, config={"CACHE_TYPE": "simple"})
    # Using Memcache
    # cache_servers = os.environ.get("MEMCACHIER_SERVERS")
    # if cache_servers == None:
    #     cache_servers = os.environ.get("MEMCACHIER_SERVERS")
    # else:
    #     cache_user = os.environ.get("MEMCACHIER_USERNAME") or ""
    #     cache_pass = os.environ.get("MEMCACHIER_PASSWORD") or ""
    #     cache.init_app(
    #         app,
    #         config={
    #             "CACHE_TYPE": "saslmemcached",
    #             "CACHE_MEMCACHED_SERVERS": cache_servers.split(","),
    #             "CACHE_MEMCACHED_USERNAME": cache_user,
    #             "CACHE_MEMCACHED_PASSWORD": cache_pass,
    #             "CACHE_OPTIONS": {
    #                 "behaviors": {
    #                     # Faster IO
    #                     "tcp_nodelay": True,
    #                     # Keep connection alive
    #                     "tcp_keepalive": True,
    #                     # Timeout for set/get requests
    #                     "connect_timeout": 2000,  # ms
    #                     "send_timeout": 750 * 1000,  # us
    #                     "receive_timeout": 750 * 1000,  # us
    #                     "_poll_timeout": 2000,  # ms
    #                     # Better failover
    #                     "ketama": True,
    #                     "remove_failed": 1,
    #                     "retry_timeout": 2,
    #                     "dead_timeout": 30,
    #                 }
    #             },
    #         },
    #     )
    #     app.config.update(
    #         SESSION_TYPE="memcached",
    #         SESSION_MEMCACHED=pylibmc.Client(
    #             cache_servers.split(","),
    #             binary=True,
    #             username=cache_user,
    #             password=cache_pass,
    #             behaviors={
    #                 # Faster IO
    #                 "tcp_nodelay": True,
    #                 # Keep connection alive
    #                 "tcp_keepalive": True,
    #                 # Timeout for set/get requests
    #                 "connect_timeout": 2000,  # ms
    #                 "send_timeout": 750 * 1000,  # us
    #                 "receive_timeout": 750 * 1000,  # us
    #                 "_poll_timeout": 2000,  # ms
    #                 # Better failover
    #                 "ketama": True,
    #                 "remove_failed": 1,
    #                 "retry_timeout": 2,
    #                 "dead_timeout": 30,
    #             },
    #         ),
    #     )

    # Blueprints
    from myMood.users.routes import users
    from myMood.stories.routes import stories
    from myMood.main.routes import main
    from myMood.errors.handlers import errors

    # register blueprints
    app.register_blueprint(users)
    app.register_blueprint(stories)
    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

myMood/main/routes.py
from flask import render_template, request, Blueprint, flash, url_for, redirect
from myMood import db, bcrypt, cache
from myMood.models import User, Post
from flask_login import current_user
from myMood.users.forms import RegisterForm
from sqlalchemy.sql.expression import func

main = Blueprint("main", __name__)


@main.route("/home", methods=["GET", "POST"])
def home():
    if current_user.is_authenticated:
        return redirect(url_for("users.dashboard"))

    form = RegisterForm()

    if request.method == "POST":
        if "agree" in request.form:
            if form.validate_on_submit():
                hashed_pass = bcrypt.generate_password_hash(form.password.data).decode(
                    "utf-8"
                )
                user = User(
                    username=form.username.data,
                    email=form.email.data,
                    password=hashed_pass,
                )
                db.session.add(user)
                db.session.commit()
                flash(
                    "Your account has been successfully created. You can now login!",
                    "success",
                )
                return redirect(url_for("users.user_login"))
        else:
            flash("Please accept the Terms and Agreement", "danger")
            return redirect(url_for("main.home"))

    return render_template("main/index.html", title="my.Mood", form=form)


@main.route("/about")
def about():
    return render_template("main/about.html", title="About")


@main.route("/discover/g")
def discover():
    users = User.query.order_by(func.random()).limit(6).all()
    stories = (
        Post.query.filter_by(state="public")
        .order_by(Post.date_posted.desc())
        .limit(7)
        .all()
    )
    return render_template(
        "main/discover.html", title="Discover", users=users, stories=stories
    )

myMood/users/routes.py
from flask import (
    render_template,
    url_for,
    flash,
    redirect,
    request,
    Blueprint,
    current_app,
    session,
)
from sqlalchemy.sql.expression import func
from flask_login import login_user, current_user, logout_user, login_required
from myMood import db, bcrypt, cache
from myMood.models import User, Post
from myMood.stories.query import (
    query_all_stories,
    query_all_public_stories,
    query_public_stories,
    query_def_stories,
    query_all_stories,
)
from myMood.users.query import (
    query_user_profile,
    query_search_user,
    query_search_stories,
)
from myMood.users.forms import (
    RegisterForm,
    LoginForm,
    FollowForm,
    ResetPassForm,
    NewPassForm,
)
from myMood.stories.forms import NewStoryForm
from myMood.main.forms import SearchForm
from myMood.users.forms_profile import (
    UpdateProfile,
    UpdateProfilePic,
    UpdateWHOAMI,
    UpdateBgImage,
    UpdateSocialLinks,
    UpdateEmail,
    UpdatePassword,
)
from myMood.users.utils import save_bg_image, save_profile_pic, send_reset_email
import os

users = Blueprint("users", __name__)


def is_post():
    return request.method == "POST"


@users.route("/user/login", methods=["GET", "POST"])
def user_login():
    # bypass if user is authenticated
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))

    form = LoginForm()

    if request.method == "POST":
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user and bcrypt.check_password_hash(user.password, form.password.data):
                session["user"] = request.form["email"]
                login_user(user, remember=form.remember.data)
                next_page = request.args.get("next")
                return (
                    redirect(next_page)
                    if next_page
                    else redirect(url_for("users.dashboard"))
                )
            else:
                flash("Incorrect Email / Password!!", "danger")

    return render_template(
        "main/login.html", form=form, form_title="Login", screen_height="h-screen"
    )


@users.route("/user/register", methods=["GET", "POST"])
def user_register():
    # bypass if user is authenticated
    if current_user.is_authenticated:
        return redirect(url_for("users.dashboard"))

    form = RegisterForm()

    if request.method == "POST":
        if "agree" in request.form:
            if form.validate_on_submit():
                hashed_pass = bcrypt.generate_password_hash(form.password.data).decode(
                    "utf-8"
                )
                user = User(
                    username=form.username.data,
                    email=form.email.data,
                    password=hashed_pass,
                )
                db.session.add(user)
                db.session.commit()
                flash(
                    "Your account has been successfully created. You can now login!",
                    "success",
                )
                return redirect(url_for("users.user_login"))
        else:
            flash("Please accept the Terms and Agreement", "danger")
            return redirect(url_for("users.user_register"))

    return render_template(
        "main/register.html", form=form, form_title="Register", screen_height="h-full"
    )


@users.route("/logout")
def user_logout():
    session.pop("user", None)
    logout_user()
    return redirect(url_for("users.user_login"))


# Dashboard Routes
@users.route("/", methods=["GET", "POST"])
def dashboard():
    if not current_user.is_authenticated:
        return redirect(url_for("main.home"))
    # s = current_user
    # page = request.args.get("stories", 1, type=int)
    s = current_user
    stories = s.followed_posts().limit(10).all()
    # stories = Post.query.filter_by(author=current_user).order_by(
    #     Post.date_posted.desc()
    # )
    # stories = Post.query.order_by(Post.date_posted.desc()).paginate(
    #     page=page, per_page=5
    # )
    form = NewStoryForm()

    if request.method == "POST":
        if form.validate_on_submit():
            story = Post(
                content=form.content.data,
                emotion=form.emotion.data,
                state=form.state.data,
                author=current_user,
            )
            db.session.add(story)
            db.session.commit()
            if request.form["state"] == "public":
                cache.delete_memoized(query_public_stories, query_all_public_stories)
            cache.delete_memoized(query_def_stories)
            return redirect(url_for("users.dashboard"))
    return render_template(
        "dashboard/index.html", form=form, dashboard_title="Home", stories=stories,
    )


# Follow User
@users.route("/follow/<user_to_follow>", methods=["POST"])
def follow_user(user_to_follow):
    formFollow = FollowForm()
    if request.method == "POST":
        if formFollow.validate_on_submit():
            target_user = User.query.filter_by(username=user_to_follow).first()
            current_user.follow(target_user)
            db.session.commit()
            cache.delete_memoized(query_user_profile, user_to_follow)
            cache.delete("user_stories")
            cache.delete_memoized(dash_profile, user_to_follow)
            return redirect(url_for("users.dash_profile", user=user_to_follow))


# Unfollow User
@users.route("/unfollow/<user_to_unfollow>", methods=["POST"])
def unfollow_user(user_to_unfollow):
    formFollow = FollowForm()
    if request.method == "POST":
        if formFollow.validate_on_submit():
            target_user = User.query.filter_by(username=user_to_unfollow).first()
            current_user.unfollow(target_user)
            db.session.commit()
            cache.delete_memoized(query_user_profile, user_to_unfollow)
            cache.delete("user_stories")
            cache.delete_memoized(dash_profile, user_to_unfollow)
            return redirect(url_for("users.dash_profile", user=user_to_unfollow))


# User Profile
@users.route("/u/<user>", methods=["GET"])
@cache.memoize()
def dash_profile(user):
    formUpProfile = UpdateProfile()
    formUpProfilePic = UpdateProfilePic()
    formUpBgImage = UpdateBgImage()
    formUpWhoami = UpdateWHOAMI()
    formUpSocialLinks = UpdateSocialLinks()
    formFollow = FollowForm()

    if request.method == "GET":
        formUpProfile.username.data = current_user.username
        formUpProfile.random_say.data = current_user.random_say
        formUpWhoami.whoami.data = current_user.whoami
        formUpSocialLinks.fb.data = current_user.social_fb
        formUpSocialLinks.tw.data = current_user.social_tw
        formUpSocialLinks.ig.data = current_user.social_ig
        formUpSocialLinks.yt.data = current_user.social_yt

    username = query_user_profile(user)
    if username != current_user:
        cache.delete_memoized(dash_profile, user)
    # stories = Post.query.filter_by(author=username).order_by(Post.date_posted.desc())
    if current_user == username:
        stories = (
            Post.query.filter_by(author=username)
            .order_by(Post.date_posted.desc())
            .limit(7)
            .all()
        )
    else:
        if current_user.is_following(username):
            stories = (
                Post.query.filter_by(author=username)
                .order_by(Post.date_posted.desc())
                .limit(7)
                .all()
            )
        else:
            stories = (
                Post.query.filter_by(author=username, state="public")
                .order_by(Post.date_posted.desc())
                .limit(7)
                .all()
            )

    return render_template(
        "dashboard/user_profile.html",
        dashboard_title=user + " - Profile",
        my_stories=stories,
        user=username,
        formUpProfile=formUpProfile,
        formUpProfilePic=formUpProfilePic,
        formUpBgImage=formUpBgImage,
        formUpWhoami=formUpWhoami,
        formUpSocialLinks=formUpSocialLinks,
        formFollow=formFollow,
    )


#:> Update User_Info Routes

# Background Profile
@users.route("/u/<user>/update?=bg_image", methods=["POST"])
def update_BgImage(user):
    formUpBgImage = UpdateBgImage()
    if request.method == "POST":
        if formUpBgImage.validate_on_submit():
            if formUpBgImage.image_background.data:
                # delete the existing background pic is it is not the default one
                if current_user.acc_image_bg != "default.jpg":
                    pp_path = os.path.join(
                        current_app.root_path,
                        "static\\profile_pics\\bg_profile",
                        current_user.acc_image_bg,
                    )
                    try:
                        os.remove(pp_path)
                    except FileNotFoundError:
                        pass

                # change the background pic
                pic_file = save_bg_image(formUpBgImage.image_background.data)
                current_user.acc_image_bg = pic_file
                db.session.commit()
                cache.delete_memoized(query_user_profile, user)
                cache.delete_memoized(dash_profile, user)
                return redirect(
                    url_for("users.dash_profile", user=current_user.username)
                )


# Profile Picture
@users.route("/u/<user>/update?=profile_pic", methods=["POST"])
def update_ProfilePic(user):
    formUpProfilePic = UpdateProfilePic()
    if request.method == "POST":
        if formUpProfilePic.validate_on_submit():
            if formUpProfilePic.profile_pic.data:
                # delete the existing profile pic is it is not the default one
                if current_user.acc_image != "default.jpg":
                    pp_path = os.path.join(
                        current_app.root_path,
                        "static\\profile_pics",

myMood/templates/base_forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ form_title }} | my.MOOD</title>
    <!-- favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <!-- main css file -->
    {% assets "main_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&family=PT+Serif:wght@400;700&display=swap" rel="stylesheet">
    <!-- alpinejs -->
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <!-- fontawesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.13.0/js/all.js"></script>
</head>
<body class="antialiased" onresize="ScrollBAR('{{ form_title }}')"  onload="ScrollBAR('{{ form_title }}')">
    <div class="{{ screen_height }} w-full hero-container flex items-center justify-center" id="formContainer">
        <div class="w-11/12 sm:w-2/3 md:w-1/2 lg:w-1/3 py-10">
            <!-- main form -->
            {% cache None %}
            <div class="flex items-center justify-center mb-2">
                <img src="{{ url_for('static', filename='logo.png') }}" alt="my.Mood" class="h-12 w-12 rounded-full">
                <h1 class="ml-2 tracking-wide text-pinkish text-3xl font-sans font-bold text-center tracking-wider">my.MOOD</h1>
            </div>
            {% endcache %}

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                    <div class="rounded py-2 px-4 text-center bg-{{ category }} text-white">
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block form_content %}

            {% endblock form_content %}
        </div>
    </div>

    <!-- for login and forgot_password forms (better responsiveness) -->
    {% cache None %}
    <script type="text/javascript">
        function ScrollBAR(page){
            var deviceHeight = screen.height;
            var cont = document.getElementById('formContainer');

            if (page == "Login" || page == "Forgot Password" || page == "Reset Password"){
                if (deviceHeight <= 570){
                    cont.classList.add('h-full');
                    cont.classList.remove('h-screen');
                }
                else{
                    cont.classList.remove('h-full');
                    cont.classList.add('h-screen');
                }
            }
        }
    </script>
    {% endcache %}
</body>
</html>

myMood/templates/base_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }} | Welcome</title>
    <!-- favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <!-- main css file -->
    {% assets "main_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&family=PT+Serif:wght@400;700&display=swap" rel="stylesheet">
    <!-- alpinejs -->
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <!-- fontawesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.13.0/js/all.js"></script>
</head>

<body class="antialiased">
    {% cache None %}
    <!-- navigation menu -->
    <div class="w-full fixed top-0 z-50">
        <nav class="py-4 sm:py-0 px-6 md:px-10 lg:px-16 mx-auto sm:flex justify-between items-center bg-white" x-data="{ open: false }">
            <div class="flex flex-row justify-between items-center text-xl font-sans font-bold">
                <div class="flex items-center">
                    <img src="{{ url_for('static', filename='logo.png') }}" alt="my.Mood" class="h-10 w-10">
                    <h1 class="ml-2 tracking-wide text-pinkish">my.MOOD</h1>
                </div>
                <div class="sm:hidden">
                    <button @click="open=!open" class="focus:outline-none"
                        @keydown.escape="open = false"
                        >
                        <i x-show="!open" class="fas fa-bars"></i>
                        <i x-show="open" class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="ml-4 sm:flex"
                    :class="{'block':open, 'hidden':!open}"
                    x-show="true"
                    @click.away = "open=false">
                <ul class="block text-center sm:flex items-center justify-between">
                    <li class="block my-3 px-3 lg:px-5"><a href="{{ url_for('main.home') }}" class="hover:text-pinkish focus:outline-alignContent">Home</a></li>
                    <li class="block my-3 px-3 lg:px-5"><a href="{{ url_for('main.discover') }}" class="hover:text-pinkish focus:outline-alignContent">Discover</a></li>
                    <li class="block my-3 px-3 lg:px-5"><a href="{{ url_for('main.about') }}" class="hover:text-pinkish focus:outline-alignContent">About Us</a></li>
                    <li class="block my-6 px-3 lg:px-5"><a href="{{ url_for('users.user_login') }}" class="text-white bg-pinkish rounded-full px-6 py-2 text-sm hover:bg-blueish focus:outline-alignContent"><i class="fas fa-user mr-2"></i>Log In</a></li>
                </ul>
            </div>
        </nav>
    </div>
    {% endcache %}

    <!-- index.html (not logged in) -->
    {% block content %}

    {% endblock content %}

    {% cache None %}
    <!-- footer -->
    <footer class="bg-white">
        <div class="w-11/12 mx-auto py-3">
            <ul class="flex justify-center">
                <li class="px-3"><a href="#" class="text-xs text-gray-600 hover:text-pinkish">Terms</a></li>
                <li class="px-3"><a href="#" class="text-xs text-gray-600 hover:text-pinkish">Privacy Policy</a></li>
                <li class="px-3"><a href="#" class="text-xs text-gray-600 hover:text-pinkish">FAQs</a></li>
            </ul>
            <p class="text-sm text-center mt-2">Copyrights &copy; my.MOOD | 2020</p>
        </div>
    </footer>
    {% endcache %}
</div>
</body>
</html>