myMood/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    search_field = StringField(validators=[DataRequired()])

    search = SubmitField()

myMood/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from flask_migrate import Migrate
from flask_compress import Compress
from flask_assets import Environment, Bundle
from flask_caching import Cache

# import pylibmc
# from flask_session import Session
from myMood.config import ProdConfig, DevConfig
import os

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = "users.user_login"
login_manager.login_message_category = "blue"
login_manager.session_protection = "strong"
mail = Mail()
compress = Compress()
cache = Cache()
assets = Environment()
# sess = Session()


def create_app(config_class=DevConfig):
    app = Flask(__name__)
    app.config.from_object(DevConfig)
    migrate = Migrate(app, db)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    compress.init_app(app)
    assets.init_app(app)
    # sess.init_app(app)

    css = Bundle("css/build.css")
    assets.register("main_css", css)

    cache.init_app(app, config={"CACHE_TYPE": "simple"})
    # Using Memcache
    # cache_servers = os.environ.get("MEMCACHIER_SERVERS")
    # if cache_servers == None:
    #     cache_servers = os.environ.get("MEMCACHIER_SERVERS")
    # else:
    #     cache_user = os.environ.get("MEMCACHIER_USERNAME") or ""
    #     cache_pass = os.environ.get("MEMCACHIER_PASSWORD") or ""
    #     cache.init_app(
    #         app,
    #         config={
    #             "CACHE_TYPE": "saslmemcached",
    #             "CACHE_MEMCACHED_SERVERS": cache_servers.split(","),
    #             "CACHE_MEMCACHED_USERNAME": cache_user,
    #             "CACHE_MEMCACHED_PASSWORD": cache_pass,
    #             "CACHE_OPTIONS": {
    #                 "behaviors": {
    #                     # Faster IO
    #                     "tcp_nodelay": True,
    #                     # Keep connection alive
    #                     "tcp_keepalive": True,
    #                     # Timeout for set/get requests
    #                     "connect_timeout": 2000,  # ms
    #                     "send_timeout": 750 * 1000,  # us
    #                     "receive_timeout": 750 * 1000,  # us
    #                     "_poll_timeout": 2000,  # ms
    #                     # Better failover
    #                     "ketama": True,
    #                     "remove_failed": 1,
    #                     "retry_timeout": 2,
    #                     "dead_timeout": 30,
    #                 }
    #             },
    #         },
    #     )
    #     app.config.update(
    #         SESSION_TYPE="memcached",
    #         SESSION_MEMCACHED=pylibmc.Client(
    #             cache_servers.split(","),
    #             binary=True,
    #             username=cache_user,
    #             password=cache_pass,
    #             behaviors={
    #                 # Faster IO
    #                 "tcp_nodelay": True,
    #                 # Keep connection alive
    #                 "tcp_keepalive": True,
    #                 # Timeout for set/get requests
    #                 "connect_timeout": 2000,  # ms
    #                 "send_timeout": 750 * 1000,  # us
    #                 "receive_timeout": 750 * 1000,  # us
    #                 "_poll_timeout": 2000,  # ms
    #                 # Better failover
    #                 "ketama": True,
    #                 "remove_failed": 1,
    #                 "retry_timeout": 2,
    #                 "dead_timeout": 30,
    #             },
    #         ),
    #     )

    # Blueprints
    from myMood.users.routes import users
    from myMood.stories.routes import stories
    from myMood.main.routes import main
    from myMood.errors.handlers import errors

    # register blueprints
    app.register_blueprint(users)
    app.register_blueprint(stories)
    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

myMood/stories/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from myMood import db, cache
from myMood.models import User, Post
from myMood.stories.forms import NewStoryForm
from myMood.stories.query import (
    query_all_public_stories,
    query_all_stories,
    query_def_stories,
    query_all_user_stories,
)

stories = Blueprint("stories", __name__)


@stories.route("/u/<user>/stories/<int:story_id>", methods=["GET"])
@cache.memoize()
def user_post(user, story_id):
    form = NewStoryForm()
    story = Post.query.get_or_404(story_id)
    if request.method == "GET":
        form.content.data = story.content
        form.emotion.data = story.emotion
        form.state.data = story.state
    return render_template(
        "dashboard/user_post.html", story=story, dashboard_title="My Story", form=form,
    )


# update post
@stories.route("/u/<user>/stories/<int:story_id>/update", methods=["GET", "POST"])
def update_post(user, story_id):
    story = Post.query.get_or_404(story_id)
    if story.author != current_user:
        return redirect(url_for("users.dash_profile", user=story.author.username))
    form = NewStoryForm()
    if request.method == "POST":
        if form.validate_on_submit():
            story.content = form.content.data
            story.emotion = form.emotion.data
            story.state = form.state.data
            db.session.commit()
            cache.delete_memoized(user_post, story.author.username, story_id)
            return redirect(
                url_for(
                    "stories.user_post", user=current_user.username, story_id=story.id
                )
            )


# delete post
@stories.route("/u/<user>/stories/<int:story_id>/delete", methods=["GET", "POST"])
def delete_post(user, story_id):
    story = query_user_story(story_id)
    if story.author != current_user:
        return redirect(url_for("users.dash_profile", user=story.author.username))
    if request.method == "POST":
        db.session.delete(story)
        db.session.commit()
        cache.delete_memoized(user_post, story.author.username, story_id)
        return redirect(url_for("users.dash_profile", user=current_user.username))


# GET ALL STORIES

# all stories with followed ones
@stories.route("/stories/all")
def all_stories():
    stories = query_all_stories()

    return render_template(
        "dashboard/all_stories.html", dashboard_title="Stories", stories=stories
    )


# stories of user only
@stories.route("/u/<user>/stories/all")
def all_user_stories(user):
    u = User.query.filter_by(username=user).first_or_404()
    stories = query_all_user_stories(u)

    if u == current_user:
        title = "My Stories"
    else:
        title = u.username + "'s Stories"

    return render_template(
        "dashboard/all_stories.html", dashboard_title=title, stories=stories
    )


# public stories only
@stories.route("/discover/stories/all")
def all_public_stories():
    stories = query_all_public_stories()

    return render_template(
        "dashboard/all_stories.html", dashboard_title="Public Stories", stories=stories
    )

myMood/users/routes.py
from flask import (
    render_template,
    url_for,
    flash,
    redirect,
    request,
    Blueprint,
    current_app,
    session,
)
from sqlalchemy.sql.expression import func
from flask_login import login_user, current_user, logout_user, login_required
from myMood import db, bcrypt, cache
from myMood.models import User, Post
from myMood.stories.query import (
    query_all_stories,
    query_all_public_stories,
    query_public_stories,
    query_def_stories,
    query_all_stories,
)
from myMood.users.query import (
    query_user_profile,
    query_search_user,
    query_search_stories,
)
from myMood.users.forms import (
    RegisterForm,
    LoginForm,
    FollowForm,
    ResetPassForm,
    NewPassForm,
)
from myMood.stories.forms import NewStoryForm
from myMood.main.forms import SearchForm
from myMood.users.forms_profile import (
    UpdateProfile,
    UpdateProfilePic,
    UpdateWHOAMI,
    UpdateBgImage,
    UpdateSocialLinks,
    UpdateEmail,
    UpdatePassword,
)
from myMood.users.utils import save_bg_image, save_profile_pic, send_reset_email
import os

users = Blueprint("users", __name__)


def is_post():
    return request.method == "POST"


@users.route("/user/login", methods=["GET", "POST"])
def user_login():
    # bypass if user is authenticated
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))

    form = LoginForm()

    if request.method == "POST":
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user and bcrypt.check_password_hash(user.password, form.password.data):
                session["user"] = request.form["email"]
                login_user(user, remember=form.remember.data)
                next_page = request.args.get("next")
                return (
                    redirect(next_page)
                    if next_page
                    else redirect(url_for("users.dashboard"))
                )
            else:
                flash("Incorrect Email / Password!!", "danger")

    return render_template(
        "main/login.html", form=form, form_title="Login", screen_height="h-screen"
    )


@users.route("/user/register", methods=["GET", "POST"])
def user_register():
    # bypass if user is authenticated
    if current_user.is_authenticated:
        return redirect(url_for("users.dashboard"))

    form = RegisterForm()

    if request.method == "POST":
        if "agree" in request.form:
            if form.validate_on_submit():
                hashed_pass = bcrypt.generate_password_hash(form.password.data).decode(
                    "utf-8"
                )
                user = User(
                    username=form.username.data,
                    email=form.email.data,
                    password=hashed_pass,
                )
                db.session.add(user)
                db.session.commit()
                flash(
                    "Your account has been successfully created. You can now login!",
                    "success",
                )
                return redirect(url_for("users.user_login"))
        else:
            flash("Please accept the Terms and Agreement", "danger")
            return redirect(url_for("users.user_register"))

    return render_template(
        "main/register.html", form=form, form_title="Register", screen_height="h-full"
    )


@users.route("/logout")
def user_logout():
    session.pop("user", None)
    logout_user()
    return redirect(url_for("users.user_login"))


# Dashboard Routes
@users.route("/", methods=["GET", "POST"])
def dashboard():
    if not current_user.is_authenticated:
        return redirect(url_for("main.home"))
    # s = current_user
    # page = request.args.get("stories", 1, type=int)
    s = current_user
    stories = s.followed_posts().limit(10).all()
    # stories = Post.query.filter_by(author=current_user).order_by(
    #     Post.date_posted.desc()
    # )
    # stories = Post.query.order_by(Post.date_posted.desc()).paginate(
    #     page=page, per_page=5
    # )
    form = NewStoryForm()

    if request.method == "POST":
        if form.validate_on_submit():
            story = Post(
                content=form.content.data,
                emotion=form.emotion.data,
                state=form.state.data,
                author=current_user,
            )
            db.session.add(story)
            db.session.commit()
            if request.form["state"] == "public":
                cache.delete_memoized(query_public_stories, query_all_public_stories)
            cache.delete_memoized(query_def_stories)
            return redirect(url_for("users.dashboard"))
    return render_template(
        "dashboard/index.html", form=form, dashboard_title="Home", stories=stories,
    )


# Follow User
@users.route("/follow/<user_to_follow>", methods=["POST"])
def follow_user(user_to_follow):
    formFollow = FollowForm()
    if request.method == "POST":
        if formFollow.validate_on_submit():
            target_user = User.query.filter_by(username=user_to_follow).first()
            current_user.follow(target_user)
            db.session.commit()
            cache.delete_memoized(query_user_profile, user_to_follow)
            cache.delete("user_stories")
            cache.delete_memoized(dash_profile, user_to_follow)
            return redirect(url_for("users.dash_profile", user=user_to_follow))


# Unfollow User
@users.route("/unfollow/<user_to_unfollow>", methods=["POST"])
def unfollow_user(user_to_unfollow):
    formFollow = FollowForm()
    if request.method == "POST":
        if formFollow.validate_on_submit():
            target_user = User.query.filter_by(username=user_to_unfollow).first()
            current_user.unfollow(target_user)
            db.session.commit()
            cache.delete_memoized(query_user_profile, user_to_unfollow)
            cache.delete("user_stories")
            cache.delete_memoized(dash_profile, user_to_unfollow)
            return redirect(url_for("users.dash_profile", user=user_to_unfollow))


# User Profile
@users.route("/u/<user>", methods=["GET"])
@cache.memoize()
def dash_profile(user):
    formUpProfile = UpdateProfile()
    formUpProfilePic = UpdateProfilePic()
    formUpBgImage = UpdateBgImage()
    formUpWhoami = UpdateWHOAMI()
    formUpSocialLinks = UpdateSocialLinks()
    formFollow = FollowForm()

    if request.method == "GET":
        formUpProfile.username.data = current_user.username
        formUpProfile.random_say.data = current_user.random_say
        formUpWhoami.whoami.data = current_user.whoami
        formUpSocialLinks.fb.data = current_user.social_fb
        formUpSocialLinks.tw.data = current_user.social_tw
        formUpSocialLinks.ig.data = current_user.social_ig
        formUpSocialLinks.yt.data = current_user.social_yt

    username = query_user_profile(user)
    if username != current_user:
        cache.delete_memoized(dash_profile, user)
    # stories = Post.query.filter_by(author=username).order_by(Post.date_posted.desc())
    if current_user == username:
        stories = (
            Post.query.filter_by(author=username)
            .order_by(Post.date_posted.desc())
            .limit(7)
            .all()
        )
    else:
        if current_user.is_following(username):
            stories = (
                Post.query.filter_by(author=username)
                .order_by(Post.date_posted.desc())
                .limit(7)
                .all()
            )
        else:
            stories = (
                Post.query.filter_by(author=username, state="public")
                .order_by(Post.date_posted.desc())
                .limit(7)
                .all()
            )

    return render_template(
        "dashboard/user_profile.html",
        dashboard_title=user + " - Profile",
        my_stories=stories,
        user=username,
        formUpProfile=formUpProfile,
        formUpProfilePic=formUpProfilePic,
        formUpBgImage=formUpBgImage,
        formUpWhoami=formUpWhoami,
        formUpSocialLinks=formUpSocialLinks,
        formFollow=formFollow,
    )


#:> Update User_Info Routes

# Background Profile
@users.route("/u/<user>/update?=bg_image", methods=["POST"])
def update_BgImage(user):
    formUpBgImage = UpdateBgImage()
    if request.method == "POST":
        if formUpBgImage.validate_on_submit():
            if formUpBgImage.image_background.data:
                # delete the existing background pic is it is not the default one
                if current_user.acc_image_bg != "default.jpg":
                    pp_path = os.path.join(
                        current_app.root_path,
                        "static\\profile_pics\\bg_profile",
                        current_user.acc_image_bg,
                    )
                    try:
                        os.remove(pp_path)
                    except FileNotFoundError:
                        pass

                # change the background pic
                pic_file = save_bg_image(formUpBgImage.image_background.data)
                current_user.acc_image_bg = pic_file
                db.session.commit()
                cache.delete_memoized(query_user_profile, user)
                cache.delete_memoized(dash_profile, user)
                return redirect(
                    url_for("users.dash_profile", user=current_user.username)
                )


# Profile Picture
@users.route("/u/<user>/update?=profile_pic", methods=["POST"])
def update_ProfilePic(user):
    formUpProfilePic = UpdateProfilePic()
    if request.method == "POST":
        if formUpProfilePic.validate_on_submit():
            if formUpProfilePic.profile_pic.data:
                # delete the existing profile pic is it is not the default one
                if current_user.acc_image != "default.jpg":
                    pp_path = os.path.join(
                        current_app.root_path,
                        "static\\profile_pics",

myMood/templates/dashboard/discover.html
{% extends "dashboard.html" %}

{% block dash_content %}
<!-- Discover -->
<div class="w-5/6 mx-auto">
    <!-- search bar -->
     <div class="w-full">
        <form action="" class="w-full flex items-center flex-row" method="post">
            {{ formSearch.hidden_tag() }}
            <div class="relative flex items-center w-full">
                <i class="fas fa-search absolute ml-4 text-gray-500" id="search-icon"></i>
                {{ formSearch.search_field(class="text-black pl-12 pr-4 py-1 tracking-wider focus:text-pinkish border-2 border-gray-500 focus:outline-none focus:border-pinkish w-full text-sm", placeholder="Search...", onfocus="iconSearch()", onblur="iconSearch()") }}
            </div>
            {{ formSearch.search(class="bg-darkish text-white py-1 px-4 border-2 border-transparent hover:bg-green hover:border-green text-sm cursor-pointer rounded") }}
        </form>
    </div>
    <!-- random users -->
    <div class="py-3">
        <h3 class="text-gray-500">Random Users</h3>
        <div class="mt-2 grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-5 gap-4 overflow-hidden">
            {% for user in users %}
            <!-- user -->
            <div href="#" class="bg-darkish rounded-md">
                <div class="relative h-40 w-full">
                    <img src="{{ url_for('static', filename='profile_pics/' + user.acc_image) }}" alt="" class="absolute w-full h-full object-cover rounded-t-md">
                </div>
                <h4 class="tracking-wide p-2 truncate text-center"><a href="{{ url_for('users.dash_profile', user=user.username) }}" class="hover:text-gray-500 tracking-wide">{{ user.username }}</a></h4>
                <div class="text-center">
                    {% if current_user.is_following(user) %}
                        <form action="{{ url_for('users.unfollow_user', user_to_unfollow=user.username) }}" method="post">
                            {{ formFollow.hidden_tag() }}
                            {{ formFollow.submit(value="Unfollow", class="bg-pinkish px-4 text-center mb-2 rounded cursor-pointer py-1 text-sm hover:bg-blue") }}
                        </form>
                    {% else %}
                        <form action="{{ url_for('users.follow_user', user_to_follow=user.username) }}" method="post">
                            {{ formFollow.hidden_tag() }}
                            {{ formFollow.submit(value="Follow", class="bg-blue px-10 text-center mb-2 rounded cursor-pointer py-1 text-sm hover:bg-pinkish") }}
                        </form>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <hr class="border-gray-500 mt-1 mb-3">

    <!-- public posts -->
    <div class="">
        <h3 class="text-gray-500">Public Stories</h3>
        <div class="pt-2">
            {% for story in stories %}
            <!-- post -->
            <div class="bg-darker p-3 rounded-lg mb-2">
                <!-- post info -->
                <div class="flex justify-between items-center">
                    <div class="flex items-center">
                        <div class="relative h-10 w-10">
                            <img src="{{ url_for('static', filename='profile_pics/' + story.author.acc_image) }}" alt="" class="absolute w-full h-full object-cover rounded-full z-0">
                        </div>
                        <div class="user-info flex flex-col">
                            <div class="flex items-center">
                                <h4 class="mx-2 text-blue tracking-wide">{{ story.author.username }}</h4>
                                {% if story.emotion == "happy" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Happy</span> 😀</p>
                                {% elif story.emotion == "blessed" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Blessed</span> 😇</p>
                                {% elif story.emotion == "loved" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Loved</span> 😍</p>
                                {% elif story.emotion == "lovely" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Lovely</span> 😊</p>
                                {% elif story.emotion == "sad" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Sad</span> 🙁</p>
                                {% elif story.emotion == "surprised" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Surprised</span> 😱</p>
                                {% elif story.emotion == "angry" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Angry</span> 😡</p>
                                {% elif story.emotion == "excited" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Excited</span> 😁</p>
                                {% elif story.emotion == "embarassed" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Embarrased</span> 😳</p>
                                {% elif story.emotion == "thankful" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Thankful</span> 🤗</p>
                                {% elif story.emotion == "in_love" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">In Love</span> 🥰</p>
                                {% elif story.emotion == "crazy" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Crazy</span> 😆</p>
                                {% elif story.emotion == "sick" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Sick</span> 🤒</p>
                                {% elif story.emotion == "tired" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Tired</span> 😓</p>
                                {% elif story.emotion == "sleepy" %}
                                    <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Sleepy</span> 🥱</p>
                                {% endif %}
                            </div>
                            <p class="ml-4 text-gray-700 post-date text-sx">on {{ story.date_posted.strftime("%B %d, %Y") }}</p>
                        </div>
                    </div>
                    <p class="pt-1 text-gray-700 post-date text-xs hidden sm:block">{{ story.date_posted.strftime("%I:%M %p") }}</p>
                </div>
                <!-- post main -->
                <div class="flex justify-center items-center feel-{{ story.emotion }} mt-2">
                    <div class="pt-5 pb-6 px-3 md:px-6 text-center">
                        <h2 class="font-bold tracking-wide text-2xl sm:text-3xl">{{ story.content }}</h2>
                    </div>
                </div>
                <p class="pt-1 text-gray-700 post-date text-xs block sm:hidden">{{ story.date_posted.strftime("%I:%M %p") }}</p>
            </div>
            {% else %}
            <!-- show text "No Posts" -->
            <div class="bg-darker p-3 rounded-lg mb-2">
                <h1 class="text-gray-200 text-xl font-bold tracking-wider">No Stories to Show</h1>
            </div>
            {% endfor %}
            <!-- more stories -->
            {% if not stories|length == 0 %}
            <a href="{{ url_for('stories.all_public_stories') }}" type="button" class="border-2 border-darkish rounded-lg text-center w-full py-1 bg-darkish text-sm hover:bg-gray-600 hover:border-gray-600">More Stories</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock dash_content %}

myMood/templates/dashboard/post_user.html
{% extends "dashboard.html" %}

{% block dash_content %}
<div class="w-5/6 mx-auto mt-8">
	<!-- posts container -->
    <div>
        {% for story in stories %}
        <!-- post -->
        <div class="bg-darker p-3 rounded-lg mb-2">
            <!-- post info -->
            <div class="flex justify-between items-center">
                <div class="flex items-center">
                    <div class="relative h-10 w-10">
                        <img src="{{ url_for('static', filename='profile_pics/' + story.author.acc_image) }}" alt="" class="absolute w-full h-full object-cover rounded-full z-0">
                    </div>
                    <div class="user-info flex flex-col">
                        <div class="flex items-center">
                            <h4 class="mx-2 text-blue tracking-wide">{{ story.author.username }}</h4>
                            {% if story.emotion == "happy" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Happy</span> 😀</p>
                            {% elif story.emotion == "blessed" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Blessed</span> 😇</p>
                            {% elif story.emotion == "loved" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Loved</span> 😍</p>
                            {% elif story.emotion == "lovely" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Lovely</span> 😊</p>
                            {% elif story.emotion == "sad" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Sad</span> 🙁</p>
                            {% elif story.emotion == "surprised" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Surprised</span> 😱</p>
                            {% elif story.emotion == "angry" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Angry</span> 😡</p>
                            {% elif story.emotion == "excited" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Excited</span> 😁</p>
                            {% elif story.emotion == "embarassed" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Embarrased</span> 😳</p>
                            {% elif story.emotion == "thankful" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Thankful</span> 🤗</p>
                            {% elif story.emotion == "in_love" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">In Love</span> 🥰</p>
                            {% elif story.emotion == "crazy" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Crazy</span> 😆</p>
                            {% elif story.emotion == "sick" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Sick</span> 🤒</p>
                            {% elif story.emotion == "tired" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Tired</span> 😓</p>
                            {% elif story.emotion == "sleepy" %}
                                <p class="text-sm mt-1 text-gray-600 emotion flex">is feeling <span class="hidden sm:block px-1">Sleepy</span> 🥱</p>
                            {% endif %}
                        </div>
                        <p class="ml-4 text-gray-700 post-date text-sx">on {{ story.date_posted.strftime("%B %d, %Y") }}</p>
                    </div>
                </div>
                <p class="pt-1 text-gray-700 post-date text-xs hidden sm:block">{{ story.date_posted.strftime("%I:%M %p") }}</p>
            </div>
            <!-- post main -->
            <div class="flex justify-center items-center feel-{{ story.emotion }} mt-2">
                <div class="pt-5 pb-6 px-3 md:px-6 text-center">
                    <h2 class="font-bold tracking-wide text-2xl sm:text-3xl">{{ story.content }}</h2>
                </div>
            </div>
            <p class="pt-1 text-gray-700 post-date text-xs block sm:hidden">{{ story.date_posted.strftime("%I:%M %p") }}</p>
        </div>
        {% else %}
        <!-- show text "No Posts" -->
        <div class="bg-darker p-3 rounded-lg mb-2">
            <h1 class="text-gray-200 text-xl font-bold tracking-wider">No Stories to Show</h1>
        </div>
        {% endfor %}
        <!-- more stories -->
        {% if not stories|length == 0 %}
        <a href="{{ url_for('stories.all_user_stories', user=u.username) }}" type="button" class="border-2 border-darkish rounded-lg text-center w-full py-1 bg-darkish text-sm hover:bg-gray-600 hover:border-gray-600">More Stories</a>
        {% endif %}
    </div>
</div>
{% endblock dash_content %}